version: '3.3'

services:
   elast-alert:
      image: bitsensor/elastalert:3.0.0-beta.1
      container_name:  elast-alert
      ports:
         - 3030:3030
      volumes:
         - "./config/elastalert.yaml:/opt/elastalert/config.yaml"
         - "./config/config.json:/opt/elastalert-server/config/config.json"
         - "./rules:/opt/elastalert/rules"
         - "./rule_templates:/opt/elastalert/rule_templates"
      networks:
        - docker-elk_elk

networks:
  docker-elk_elk:
    external: true


