version: '3.2'

services:
  nginx:
    image: nginx:latest
    ports:
        - 80:80
        - 9200:9200
    volumes:
        - ./config/:/etc/nginx/conf.d/
    command: /bin/bash -c "nginx -g 'daemon off;'"
    networks:
        - docker-elk_elk

networks:
  docker-elk_elk:
    external: true

