version: '3.2'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./esdata1:/usr/share/elasticsearch/data:rw
      - ./tls/elasticsearch/elasticsearch.p12:/usr/share/elasticsearch/config/elasticsearch.p12:ro
      - ./tls/elasticsearch/http.p12:/usr/share/elasticsearch/config/http.p12:ro
    ports:
      - "9201:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx2g -Xms2g"
      ELASTIC_PASSWORD: ${ELASTICSEARCH_PASSWORD}
      ELASTICSEARCH1_IP: ${ELASTICSEARCH1_IP}
      ELASTICSEARCH2_IP: ${ELASTICSEARCH2_IP}
      NODE_NAME: $HOSTNAME  
    
    network_mode: host      

  
  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: false
      - ./tls/kibana/elasticsearch-ca.pem:/usr/share/kibana/config/elasticsearch-ca.pem:ro
    environment:
      ELASTICSEARCH_HOST: $ELASTICSEARCH_HOST
      ELASTICSEARCH_PORT: $ELASTICSEARCH_PORT
      ELASTICSEARCH_USERNAME: $ELASTICSEARCH_USERNAME
      ELASTICSEARCH_PASSWORD: $ELASTICSEARCH_PASSWORD
    ports:
      - "5601:5601"
      #- "80:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  metricbeat:
    user: root
    build:
      context: metricbeat/
      args:
        ELK_VERSION: $ELK_VERSION
    command: ["--strict.perms=false", "-system.hostfs=/hostfs"]
    volumes:
      #- type: bind
      #  source: ./metricbeat/config/metricbeat.yml
       # target: /usr/share/metricbeat/metricbeat.yml
       # read_only: false
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock      
    environment:
      LS_JAVA_OPTS: "-Xmx515m -Xms512m"
      ELASTICSEARCH_HOST: $ELASTICSEARCH_HOST
      ELASTICSEARCH_PORT: $ELASTICSEARCH_PORT
      ELASTICSEARCH_USERNAME: $ELASTICSEARCH_USERNAME
      ELASTICSEARCH_PASSWORD: $ELASTICSEARCH_PASSWORD
      KIBANA_HOST: $KIBANA_HOST
      KIBANA_PORT: $KIBANA_PORT
    network_mode: host
    depends_on:
      - kibana 
networks:
  elk:
    driver: bridge
volumes:
  elasticsearch:
